name: Python CI
on:
  push:
  pull_request:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.12'
      - name: check python
        run: python3 --version
      - name: CI Success
        run: echo "Python CI pipeline finished" 
